### ISSUE TITLE
`BasicFormat` doesn't add spaces between first and second parameter name

### ISSUE THREAD

**Issue by stevapple** [swiftlang/swift-syntax#1505]
### Description

When using `FunctionParameterSyntax` with `SwiftSyntaxBuilder`, the build result (formatted by `BasicFormat`) doesn't have spaces between first and second parameter names, which is "lexically legal" but far against user intention.

### Steps to Reproduce

```swift
let parameter = FunctionParameterSyntax(firstName: "on", secondName: "eventLoop", colon: .colonToken(), type: TypeSyntax("EventLoop"))
print(parameter) // oneventLoop: EventLoop
```

**Comment by ahoppen** [comment]
rdar://107787208
