### ISSUE TITLE
`PrecedenceGroupRelationSyntax.higherThanOrLowerThan` should be named `higherThanOrLowerThanKeyword`

### ISSUE THREAD

**Issue by AnthonyLatsis** [swiftlang/swift-syntax#1747]
### Description

The current name is inconsistent with `PrecedenceGroupAssignmentSyntax.assignmentKeyword` and `PrecedenceGroupAssociativitySyntax.associativityKeyword`.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://110482259
