### ISSUE TITLE
Document environment variables that can be used to modify swift-syntax’s build or test execution

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/swift-syntax#1922]
We should have a single documentation document that describes all the environment variables that can be used to modify the behavior of Package.swift (e.g. `SWIFT_BUILD_SCRIPT_ENVIRONMENT`) and test execution (e.g. `SKIP_LONG_TESTS`)

**Comment by ShaniDan** [comment]
Hi,
I'd like to contribute to this as part of the Swift Mentorship program.

**Comment by ahoppen** [comment]
Hi @ShaniDan,
The [Swift Mentorship Program](https://www.swift.org/mentorship/) has already started but you can definitely work on this, just like other open source contributors do. 👍🏽

**Comment by ShaniDan** [comment]
@ahoppen Yes, the program has already started and I'm one of the current mentees on the program. I already started researching on how to properly document the environment variables and my mentor is guiding me on it.

The comment says there should be a single documentation on all the variables that can be used to modify the behavior of the Package.swift. 
Could you please elaborate on the explanation? 

Thank you!

**Comment by ahoppen** [comment]
I am referring to the environment variables that are checked in Package.swift (and the entire package) like here

https://github.com/apple/swift-syntax/blob/1e8b158e30c6b0a592a0c060fdcb9d2e15064d23/Package.swift#L12

Basically, searching for `ProcessInfo.processInfo.environment` in the repository should show all of them.
