### ISSUE TITLE
Disallow multiline strings in `#sourceLocation` filename

### ISSUE THREAD

**Issue by kimdv** [swiftlang/swift-syntax#2002]
### Issue Kind

Bad Diagnostic Produced

### Source Code

```swift
      #sourceLocation(file: """
      test.swift
      other.swift
      """, line: 10)
```

Is accepted and shouldn't be allowed

**Comment by ahoppen** [comment]
The same applies to almost all other syntax nodes that contain a `StringLiteralExprSyntax`.

- `AttributeSyntax.arguments` (used for `@_cdecl` and `@_semantics`)
- `AvailabilityLabeledArgumentSyntax.value`
- `ConventionAttributeArgumentsSyntax.cTypeString`
- `DocumentationAttributeArgumentSyntax.value`
- `ExposeAttributeArgumentsSyntax.cxxName`
- `OpaqueReturnTypeOfAttributeArgumentsSyntax.mangledName`
- `OriginallyDefinedInAttributeArgumentsSyntax.moduleName`
- `PoundSourceLocationArgumentsSyntax.fileName`
- `UnavailableFromAsyncAttributeArgumentsSyntax.message`
- `UnderscorePrivateAttributeArgumentsSyntax.filename`

**Comment by ahoppen** [comment]
Decided that we should allow multi-line string literals here. See https://github.com/apple/swift/pull/71366
