### ISSUE TITLE
Sometimes the placeholder is identified as IdentifierPattern

### ISSUE THREAD

**Issue by HassanTaleb90** [swiftlang/swift-syntax#2147]
### Description

Sometimes the placeholder is identified as IdentifierPattern and not as EditorPlaceholderExpr.

### Steps to Reproduce

```
let <#name#> = <#value#>
```
<#name#> //Bug:  is identified as `IdentifierPattern`
<#value#> //Normal: is identified as `EditorPlaceholderExpr`

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://114896000
