### ISSUE TITLE
Support parsing of editor placeholders in type positions

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/swift-syntax#2156]
### Issue Kind

Other

### Source Code

```swift
let a: <#T#> = x
```

### Description

`<#T#>` currently gets parsed as a `NamedOpaqueReturnTypeSyntax`. We should create a `EditorPlaceholderTypeSyntax` node and parse `<#T#>` as an editor placeholder.

**Comment by kimdv** [comment]
I can resolve it with this PR: https://github.com/apple/swift-syntax/pull/2150

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://115028807
