### ISSUE TITLE
Introduce `FixIt.Change` API that replaces the child of a syntax node

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/swift-syntax#2205]
Currently, Fix-Its are only able to replace syntax nodes but that makes it impossible to replace a `nil` node by a proper syntax node. 

We should offer a `FixIt.Change` that replaces the child of a syntax node, with a signature that’s something like this (written in GitHub, not sure if it compiles, but it gets the idea across).

```swift
FixIt.Change.replaceChild<Parent, Child>(_: KeyPath<Parent, Child>, of parent: Parent, with: Child)
```

`FixItApplier` will need to be updated to also handle this new change kind

rdar://115562892

**Comment by mininny** [comment]
I'd like to have a go at this if it's okay!

**Comment by kimdv** [comment]
@mininny it now yours :D

**Comment by AppAppWorks** [comment]
@ahoppen, I wanted to tackle this issue but apparently there's no way to make `WritableKeyPath` conform with `Sendable` 🤷‍♂️

**Comment by ahoppen** [comment]
You should be able to always use `WritableKeyPath & Sendable`, similar to

https://github.com/swiftlang/swift-syntax/blob/d181e99d0710ca712d64f22a4d15a2c2ea24f612/Sources/SwiftSyntax/SyntaxNodeStructure.swift#L21

**Comment by AppAppWorks** [comment]
What could be the use cases for `replaceChild`?

**Comment by j-f1** [comment]
One use case (that I ran into recently) is adding a return type to a function declaration that doesn’t have one. Or potentially appending/removing a parameter.
