### ISSUE TITLE
Parsing of closure parameter list without parameter name fails

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/swift-syntax#2331]
### Issue Kind

Parse of Valid Source Failed

### Source Code

```swift
func test(_: ([Int]) -> Void) {}
test { ([Int]) in }
```

### Description

The above code is valid in the old parser but not in `SwiftParser`.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://118012839

**Comment by AnthonyLatsis** [comment]
Also `test { ([X:Y]) in }`.

**Comment by ahoppen** [comment]
Omitting the parameter’s name has never been an officially accepted language feature and the Swift grammar also requires a parameter name (https://docs.swift.org/swift-book/documentation/the-swift-programming-language/expressions#Capture-Lists). 

The warning in the C++ parser should be an error, which I’m changing in https://github.com/apple/swift/pull/70065. So, the new parser behaves correctly. Closing this issue.
