### ISSUE TITLE
Build performance issue of swift-testing

### ISSUE THREAD

**Issue by Kyle-Ye** [swiftlang/swift-syntax#2414]
### Description

Before migrating to use "swift-testing", one of my package's average CI time is as the following

<table>
<tr>
 <td> XCTest
 <td> macOS 13 + Swift 5.9.2
 <td> Ubuntu + Swift 5.9.2
<tr>
 <td> Swift Test(Debug+Covage)
 <td> 45s
 <td> 20s
<tr>
 <td> Swift Test(Release)
 <td> 34s
 <td> 27s
</table>

Most the job will do its job less in 1 min.

However after fully migrate all my test case to swift-testing, the CI time exploded especially with Release configuration.

### Expected behavior

It is expected the build time will increase due to the usage of swift macro. And 2~3 min looks normal and acceptable. 

Increased to more than 10 min is definitely means something is wrong here IMO.

And my question is the following:

1. Is this a known issue?
2. Is this expected for Swift 5.9 (or 5.10) client only and the issue will not happen for Swift Snapshots toolchain?
3. Is there a workaround for this currently?

### Actual behavior

<table>
<tr>
 <td> Testing
 <td> macOS 13 + Swift 5.9.2
 <td> Ubuntu + Swift 5.9.2
<tr>
 <td> Swift Test(Debug+Covage)
 <td> 4min3s
 <td> 3min24s
<tr>
 <td> Swift Test(Release)
 <td> 11min19s
 <td> 12min37s
</table>

### swift-testing version/commit hash

swift-testing 0.2

### Swift & OS version (output of `swift --version ; uname -a`)

Swift 5.9.2

**Comment by ahoppen** [comment]
`Empty.swift` is a red herring here. `SwiftSyntax509` depends on `SwiftSyntax` and you’re most likely seeing the compile times of the `SwiftSyntax` module while SwiftPM displays `Empty.swift`.

The underlying issue here is that swift-syntax needs to be built to use the macros in swift-testing and that release builds of swift-syntax take a while (https://github.com/apple/swift-syntax/issues/1194).

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://120672412

**Comment by Kyle-Ye** [comment]
The time has greatly improved with the new macOS 14 runner + Xcode 15.3 + Swift 5.10

It may be a combination of the upgrade of the GitHub macOS 14 image to a 4-core CPU and Swift-syntax optimization.

<table>
<tr>
 <td> Testing
 <td> macOS 13 + Swift 5.9.2
 <td> macOS 14 + Swift 5.10
<tr>
 <td> Swift Test(Debug+Covage)
 <td> 4min3s
 <td> 1min24s
<tr>
 <td> Swift Test(Release)
 <td> 11min19s
 <td> 3min21s
</table>

Although there is still a gap with the original XCTest branch, the current time result has fallen back to our acceptable range.

**Comment by bnbarham** [comment]
Swift Testing is now in the toolchain in 6.0, so there won't be any swift-syntax/swift-testing building time contributing to the tests now. Happy to close out @Kyle-Ye or are you seeing other issues?

**Comment by Kyle-Ye** [comment]
No. Have upgraded my package to Swift 6 + Xcode 16.0.

The test time if 44s for debug test and 30s for release test.

Looks good to me on Darwin platform. 

But I'd like to confirm and close it after I confirm the result on other platform this weekend. (eg. Ubuntu and WASI)

**Comment by bnbarham** [comment]
Thanks, let me know!

**Comment by Kyle-Ye** [comment]
Confirmed with Linux + Testing. No issue here too.

And WASI has no official release so I'll skip it.
