### ISSUE TITLE
`DiagnosticsFormatter` crashes when source code contains an emoji

### ISSUE THREAD

**Issue by Matejkob** [swiftlang/swift-syntax#2507]
### Description

`DiagnosticsFormatter` crashes with a  `Fatal error: Range requires lowerBound <= upperBound` message when the source code contains an emoji. 

![Screenshot 2024-02-21 at 10 51 44 PM](https://github.com/apple/swift-syntax/assets/44930823/93160b62-7b19-46b4-8bf0-f3f4ceb5d21e)

### Steps to Reproduce

Run: 

```bash
swift run swift-parser-cli print-diags -s 'func o() {
  _ = {
    0
    /x}}1️⃣} /
    2
  }
}'
```

This version:
```bash
swift run swift-parser-cli print-diags -s 'func o() {
  _ = {
    0
    /x}}$} /
    2
  }
}'
```
works.

Tested on `main`.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://123409748
