### ISSUE TITLE
New 600.0.0 prerelease

### ISSUE THREAD

**Issue by SimplyDanny** [swiftlang/swift-syntax#2747]
The latest prerelease is already more than one month old and is lacking a few fixes in the Bazel build. I'd like to integrate the parser in the next SwiftLint release to have it support Swift 6 syntax for the folks already experimenting with the new language features.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://132166848

**Comment by ahoppen** [comment]
Release created: https://github.com/swiftlang/swift-syntax/releases/tag/600.0.0-prerelease-2024-07-24

**Comment by SimplyDanny** [comment]
Thank you!
