### ISSUE TITLE
[Parser] Misparsed function parameter with keyword argument '_const'

### ISSUE THREAD

**Issue by AppAppWorks** [swiftlang/swift-syntax#2771]
### Description

One would expect `FunctionParameterSyntax.firstName` to be `"_const"`,

```swift
func const(_const map: String) {}
```

However the parser incorrectly recognizes `_const` as `DeclModifier`, and `FunctionParameterSyntax.firstName` becomes `"map"`.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://133105836
