### ISSUE TITLE
DeclModifierListSyntax adds redundant space after private modifier

### ISSUE THREAD

**Issue by yapryntsev** [swiftlang/swift-syntax#2820]
### Description

I'm trying to add a `private(set)` modifier to the property declaration but encounter a space character between the private keyword and the left paren.

### Steps to Reproduce

```swift
DeclModifierSyntax(
    name: .keyword(.private),
    detail: .init(
        leftParen: .leftParenToken(),
        detail: .identifier("set"),
        rightParen: .rightParenToken()
    )
)
```

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://134622020

**Comment by ahoppen** [comment]
Which version of swift-syntax are you using? I couldn’t reproduce it with the [latests 600 prerelease](https://github.com/swiftlang/swift-syntax/releases/tag/600.0.0-prerelease-2024-08-14), so I believe this has already been fixed.
