### ISSUE TITLE
swift format fails when using new `sending` keyword

### ISSUE THREAD

**Issue by fabianfett** [swiftlang/swift-syntax#2836]
swift format fails when using new `sending` keyword.

### Steps To Reproduce:

1. Create a Foo.swift with following content and save:

  ```
  struct Foo {
    var bar: String
  }

  func whatever(_ foo: sending Foo) {
  
  }
  ```

2. Run `swift format Foo.swift` on cli.

#### Observed:
Invocation fails: /Users/fabian/Developer/test.swift:5:30: error: unexpected code 'Foo' in parameter clause.

#### Expected:
`swift format` succeeds.

### Notes:

Fails with Swift from Xcode-beta and swift-6.0-nightly on linux.

**Comment by ahoppen** [comment]
Should be fixed by:
- `main`: https://github.com/swiftlang/swift-syntax/pull/2835
- `release/6.0`: https://github.com/swiftlang/swift-syntax/pull/2837
- `release/6.0.0`: https://github.com/swiftlang/swift-syntax/pull/2838
- `release/6.0.1`: https://github.com/swiftlang/swift-syntax/pull/2839
