### ISSUE TITLE
Invalid semantic versioning?

### ISSUE THREAD

**Issue by damian-rzeszot** [swiftlang/swift-syntax#2845]
### Description

According to the [SemVer rules](https://semver.org/#spec-item-9) numeric identifiers must not have leading zeroes.
Tags that contain a date (e.g.  [600.0.0-prerelease-2024-08-20](https://github.com/swiftlang/swift-syntax/releases/tag/600.0.0-prerelease-2024-08-20)) are quite controversial.

So here's my question: what should be in your opinion? and who should take care of the correction (semver)?

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://135540169

**Comment by ahoppen** [comment]
I don’t see any issue with our versioning. The section you quote says *Identifiers MUST NOT be empty* but *Identifier* refers to `prerelease-2024-08-20`, which doesn’t start with a leading zero. It even includes an example `1.0.0-alpha`, which matches the format of `600.0.0-prerelease-2024-08-20`.
