### ISSUE TITLE
Swift Syntax unexpectedly builds X86 libraries on ARM Mac

### ISSUE THREAD

**Issue by gestrich** [swiftlang/swift-syntax#2898]
### Description

I have an iOS project that uses Swift macros. On my new MacBook Pro (ARM), I notice that it builds for both x86 and ARM. I don't see any need for x86 build steps in this process.

I also reported this in the swift forums.

### Steps to Reproduce

You can reproduce this issue with a new simple project that includes macros or by using one of the projects I found [here](https://github.com/devashree-shukla/SwiftMacro). Just build on an arm base mac and you will see x86 compilation steps.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://140157670

**Comment by ahoppen** [comment]
It looks like this is an issue with how Xcode builds SwiftPM projects, not an issue with swift-syntax itself. Could you report this at http://feedbackassistant.apple.com?

**Comment by gestrich** [comment]
Filed with FB15945737
