### ISSUE TITLE
Printed string literal expressions are not escaped correctly

### ISSUE THREAD

**Issue by fwcd** [swiftlang/swift-syntax#549]
Printed string literal expressions are not escaped correctly (with backslashes) when generated programmatically. I stumbled upon this while beginning to port `BuildableNodes.swift.gyb` to `SwiftSyntaxBuilderGeneration`, since the template generates such literals.

Consider the following example:

```swift
import SwiftSyntaxBuilder

let source = SourceFile {
  StringLiteralExpr("\\")
}

let syntax = source.buildSyntax(format: Format())
print(syntax.description)
```

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-syntax/issues).

### Expected behavior

The example should print `"\\"`.

### Actual behavior

The example prints `"\"`, leaving the string literal unterminated.

### Steps to Reproduce

Run the program above.

**Comment by ahoppen** [comment]
rdar://98129594

**Comment by fwcd** [comment]
Closing as being the intended behavior as per our discussion.
