### ISSUE TITLE
Printed identifiers that match keywords are not escaped in backticks

### ISSUE THREAD

**Issue by fwcd** [swiftlang/swift-syntax#554]
Similar to #549, identifiers that match a reserved keyword are not escaped using backticks. Consider the following program:

```swift
import SwiftSyntaxBuilder

let source = SourceFile {
  VariableDecl(.let, name: "else", initializer: "3")
}

let syntax = source.buildSyntax(format: Format())
print(syntax.description)
```

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-syntax/issues).

### Expected behavior

The program should print

```swift
let `else` = 3
```

### Actual behavior

The program prints

```swift
let else = 3
```

### Steps to Reproduce

Run the program above.

**Comment by fwcd** [comment]
This should by the way also make subtle logic errors like generating `nil` as identifier instead of `NilLiteralExpr` (as e.g. fixed in #552) much more apparent, since, once this is fixed, the generated snippet would read
```
`nil`
```

**Comment by ahoppen** [comment]
rdar://98134904

**Comment by fwcd** [comment]
Closing as being the intended behavior as per our discussion.
