### ISSUE TITLE
SwiftSyntaxBuilderGeneration Cannot Depend on SwiftSyntaxBuilder

### ISSUE THREAD

**Issue by CodaFi** [swiftlang/swift-syntax#577]
This creates a chicken-and-egg problem when any aspect of the syntax nodes changes that also affects the builders. Consider the addition of a hypothetical node `FooSyntax`. When a user goes to update their checkouts and reruns the code generation script, they are greeted with a build failure. At first blush, this is because `ExpressibleByFooSyntax` is not regenerated by `build-script.py generate-source-code`. So the next thought would then be - just `swift run SwiftSyntaxBuilderGeneration` and regenerate the builder. But! that module no longer builds thanks to the prior source code generation script invocation.

Okay, so start over. Regenerate the builders, then regenerate syntax. Also doesn't work - the builder depends on the updated syntax nodes being present. But in order to do that... you have to run `build-script.py generate-source-code`.

Going forward, there cannot be a dependency between these two modules. We must be able to bootstrap SwiftSyntax when things change here.

**Comment by fwcd** [comment]
This is a valid point and a problem inherent to bootstrapping: If we want to use `SwiftSyntaxBuilder` to generate part of itself, it has to depend on itself in some form. However, I see that this could become an issue when trying to extend the syntax.

One solution I could think of would be to pin down a version of `SwiftSyntaxBuilder` (e.g. to the last Swift release?) That would prevent to from using any newer language features in the generated files, but I don't think that would be a big issue. Since I don't think a package can depend on an older version of itself, this might involve moving `SwiftSyntaxBuilderGeneration` to another repo, which might require some changes to the build infrastructure.

If everything else fails, we could of course also go back to the gyb-generation we had earlier, although it would be nice if we could find a solution that doesn't involve discarding all of the work done on porting the templates to Swift.

cc @ahoppen @kimdv

**Comment by ahoppen** [comment]
rdar://98765046

**Comment by ahoppen** [comment]
The underlying issue is solved by https://github.com/apple/swift-syntax/pull/583, which also has some more explanation.

**Comment by CodaFi** [comment]
Reopening this issue because it has not been resolved. As long as this tool is defined in terms of itself, it's possible for changes that are made to mainline and immediately consumed to harm the builds of people that do not have their generated copy of the code match ToT. 

We ought to remove the `--gyb-only` option since that's just a way to skip the first stage of bootstrapping and will basically never do the right thing. I still think we ought to consider splitting this tool out of the main repository.

**Comment by CodaFi** [comment]
Consider adding a syntax node `FooSyntax` and a new API `format2`. In stage 1, we regenerate the SwiftSyntaxBuilder code, which generates the Swift node definitions including `FooSyntax`, then uses those to lay down the sources for the next version of the tool that calls `format2`. Now you have a situation where the new syntax node is present in the manifest, the new API is present in the builder generation tool, but the node hasn't been regenerated in SwiftSyntax yet.

💥 

In order to wind up in this scenario, consider an engineer that is working on a new syntax node. Independently, an engineer goes to update the builder tool and commits to the remote swift-syntax. The engineer rebases onto main and the sum of their changes and the new mainline means the repo is in a state where you're 
1) defining a new node
2) defining a new API that is immediately consumed
Tada.

**Comment by fwcd** [comment]
> Independently, we ought to remove the --gyb-only option since that's just a way to skip the first stage of bootstrapping and will basically never do the right thing.

I'd like to keep this option. We do the right thing by default and when the extra flexibility is needed (which can sometimes be the case while working on the generator), the flag should be pretty self-explanatory. See https://github.com/apple/swift-syntax/pull/481.

**Comment by ahoppen** [comment]
> In order to wind up in this scenario, consider an engineer that is working on a new syntax node. Independently, an engineer goes to update the builder tool and commits to the remote swift-syntax. The first engineer locally rebases onto main and the sum of their changes and the new mainline means the repo is in a state where you're
> 
> 1. defining a new node
> 2. defining a new API that is immediately consumed
>    Tada.

I’m not saying this is the permanent solution, but a workaround for this problem would be that this engineer 
- Rebases
- Discards all his generated changes
- Re-runs code generation
- 🎉 

The more I think about it, I believe that https://github.com/apple/swift-syntax/pull/580 might be the proper solution here.

**Comment by fwcd** [comment]
> - Rebases
> - Discards all his generated changes
> - Re-runs code generation

That is what I usually do too, but perhaps not that intuitive to anyone unfamiliar with the generation process. Maybe we could simplify this workflow by adding a command to the build script that performs this particular restore?

But yeah, #580 might be an option too.

**Comment by CodaFi** [comment]
As SwiftSyntax becomes a more critical part of the workflow of those building and working with the swift compiler, this kind of workflow must be streamlined. I don’t want to paper over this with yet more build script infrastructure. This is fundamentally a layering issue with the builders and we should resolve it by either splitting them out or redoing the layering.

**Comment by CodaFi** [comment]
In that sense, even #580 may not be enough. Just as much build script chicanery would be necessary to keep the builders in sync with the main repo on the critical path.

**Comment by ahoppen** [comment]
rdar://100158743

**Comment by ahoppen** [comment]
This should be resolved by https://github.com/apple/swift-syntax/pull/826
