### ISSUE TITLE
Failure to make progress in loop on invalid code

### ISSUE THREAD

**Issue by DougGregor** [swiftlang/swift-syntax#770]
### Issue Kind

Parser Crash

### Source Code

```swift
protocol P{{}case
```

**Comment by ahoppen** [comment]
rdar://99766200

**Comment by CodaFi** [comment]
This one is another regression from the eat->expect case. `expect` and `canRecoverTo` have different precedence models and in this case the braces are too strong for `expect` to overcome. We need to forward the consumption handles or pick a different primitive.
