### ISSUE TITLE
ObjectLiteralExprSyntax parsed as MacroExpansionExprSyntax

### ISSUE THREAD

**Issue by jpsim** [swiftlang/swift-syntax#996]
### Issue Kind

Parse of Valid Source Produced Invalid Syntax Tree

### Source Code

```swift
let image = #imageLiteral(resourceName: "image.jpg")
```

### Description

Before #969 ([before.txt](https://github.com/apple/swift-syntax/files/9832022/before.txt)): `ObjectLiteralExprSyntax`
After #969 ([after.txt](https://github.com/apple/swift-syntax/files/9832023/after.txt)): `MacroExpansionExprSyntax`

**Comment by allevato** [comment]
This looks like an intentional change: https://github.com/apple/swift-syntax/pull/969/commits/85af5e9c22079fcdde63fc8421d57edd97744edf

**Comment by jpsim** [comment]
I see, thanks for the link!
